#!/bin/sh
# entrypoint.sh — render dnsmasq config from env, exec dnsmasq.
#
# Env (all required, defaults shown in Dockerfile):
#   LISTEN_IF      interface to bind to (e.g. eth1)
#   NETWORK        network address (e.g. 192.168.75.0)
#   NETMASK        e.g. 255.255.255.0
#   PREFIX         CIDR prefix (e.g. 24)
#   SELF_IP        this container's IP on the bridge (e.g. 192.168.75.2)
#   GATEWAY        gateway IP advertised to DHCP clients (e.g. 192.168.75.1
#                  — the firewall container's IP)
#   DNS_SERVER     DNS server advertised to DHCP clients (typically same
#                  as GATEWAY — firewall does DNS forwarding)
#   RANGE_START    DHCP scope start
#   RANGE_END      DHCP scope end
#   LEASE_TIME     lease length (e.g. 12h)
#   DOMAIN         search domain (e.g. otlab.local)
#   LOG_DHCP       1 to log every lease/release/etc.

set -eu

CFG=/etc/dnsmasq-otlab.conf

cat >"$CFG" <<EOF
# Auto-generated by entrypoint.sh — do not edit.
# OTLab DHCP server for ${LISTEN_IF} (${NETWORK}/${PREFIX})

# DHCP only — no DNS resolution. Devices use \$DNS_SERVER (firewall
# container) for DNS, which forwards to upstream.
port=0

# Bind only to our zone interface; don't grab unrelated bridges.
interface=${LISTEN_IF}
bind-interfaces
listen-address=${SELF_IP}

# DHCP scope
dhcp-range=${RANGE_START},${RANGE_END},${NETMASK},${LEASE_TIME}

# Advertise the firewall container as gateway + DNS.
# Option 3 = router (default gateway), option 6 = DNS.
dhcp-option=3,${GATEWAY}
dhcp-option=6,${DNS_SERVER}
dhcp-option=15,${DOMAIN}

# Don't function as a DNS server (port=0 above), but if we did,
# upstream would be the firewall container.
# server=${DNS_SERVER}

# Authoritative on this segment — speed up DHCPNAK on stale leases.
dhcp-authoritative

# Lease database lives on tmpfs — that's fine for a teaching lab.
dhcp-leasefile=/var/lib/misc/dnsmasq.leases

# Log every DHCP transaction to a file the dashboard can tail later.
$([ "${LOG_DHCP}" = "1" ] && echo "log-dhcp")
$([ "${LOG_DHCP}" = "1" ] && echo "log-facility=/var/log/dnsmasq.log")

# Per-zone reserved leases — keep known IPs sticky regardless of any
# device-side static config getting clobbered. Add your physical-Pi MACs
# here once known. Format: dhcp-host=<MAC>,<NAME>,<IP>
# Example (uncomment + edit):
# dhcp-host=2c:cf:67:4f:d3:09,l1-plc-01,10.20.30.47
# dhcp-host=b8:27:eb:78:85:77,l1-hp-01,10.20.30.48

EOF

# Wait for the listen interface to actually exist. Containerlab attaches
# the bridge-side veth (eth1) AFTER the container's entrypoint starts,
# so on cold start dnsmasq sees "unknown interface eth1" and crashes.
# Loop until the kernel reports the interface is present.
echo "==> waiting for ${LISTEN_IF} to be attached..."
for _ in $(seq 1 60); do
    if ip link show "${LISTEN_IF}" >/dev/null 2>&1; then
        break
    fi
    sleep 0.5
done
if ! ip link show "${LISTEN_IF}" >/dev/null 2>&1; then
    echo "FATAL: ${LISTEN_IF} never appeared after 30s — clab link missing?" >&2
    exit 1
fi

# Configure our own IP on the listen interface (containerlab's exec hooks
# may also do this — but on the first run we may beat them to it; on
# subsequent runs they've already done it. `ip addr replace` is a safe
# upsert either way).
ip addr replace "${SELF_IP}/${PREFIX}" dev "${LISTEN_IF}" 2>/dev/null || true
ip link set "${LISTEN_IF}" up 2>/dev/null || true

echo "==> OTLab DHCP starting"
echo "    interface : ${LISTEN_IF}"
echo "    network   : ${NETWORK}/${PREFIX}"
echo "    self      : ${SELF_IP}"
echo "    gateway   : ${GATEWAY}"
echo "    DNS       : ${DNS_SERVER}"
echo "    scope     : ${RANGE_START} -- ${RANGE_END}"
echo "    lease     : ${LEASE_TIME}"

exec dnsmasq --keep-in-foreground --conf-file="$CFG" --no-resolv --no-hosts
