#!/bin/sh
# entrypoint.sh — render dnsmasq config from env, exec dnsmasq.
#
# Env (all required, defaults shown in Dockerfile):
#   LISTEN_IF      interface to bind to (e.g. eth1)
#   NETWORK        network address (e.g. 192.168.75.0)
#   NETMASK        e.g. 255.255.255.0
#   PREFIX         CIDR prefix (e.g. 24)
#   SELF_IP        this container's IP on the bridge (e.g. 192.168.75.2)
#   GATEWAY        gateway IP advertised to DHCP clients (e.g. 192.168.75.1
#                  — the firewall container's IP)
#   DNS_SERVER     DNS server advertised to DHCP clients (typically same
#                  as GATEWAY — firewall does DNS forwarding)
#   RANGE_START    DHCP scope start
#   RANGE_END      DHCP scope end
#   LEASE_TIME     lease length (e.g. 12h)
#   DOMAIN         search domain (e.g. otlab.local)
#   LOG_DHCP       1 to log every lease/release/etc.

set -eu

CFG=/etc/dnsmasq-otlab.conf

cat >"$CFG" <<EOF
# Auto-generated by entrypoint.sh — do not edit.
# OTLab DHCP server for ${LISTEN_IF} (${NETWORK}/${PREFIX})

# DHCP only — no DNS resolution. Devices use \$DNS_SERVER (firewall
# container) for DNS, which forwards to upstream.
port=0

# Bind only to our zone interface; don't grab unrelated bridges.
interface=${LISTEN_IF}
bind-interfaces
listen-address=${SELF_IP}

# DHCP scope
dhcp-range=${RANGE_START},${RANGE_END},${NETMASK},${LEASE_TIME}

# Advertise the firewall container as gateway + DNS.
# Option 3 = router (default gateway), option 6 = DNS.
dhcp-option=3,${GATEWAY}
dhcp-option=6,${DNS_SERVER}
dhcp-option=15,${DOMAIN}

# Don't function as a DNS server (port=0 above), but if we did,
# upstream would be the firewall container.
# server=${DNS_SERVER}

# Authoritative on this segment — speed up DHCPNAK on stale leases.
dhcp-authoritative

# Lease database — written to a path that's also bind-mounted into the
# dashboard container so the leases show up live in the UI. Defaults to
# the in-container default if LEASE_FILE env isn't set (V1 fallback).
dhcp-leasefile=${LEASE_FILE:-/var/lib/misc/dnsmasq.leases}

# Log every DHCP transaction to a file the dashboard can tail later.
$([ "${LOG_DHCP}" = "1" ] && echo "log-dhcp")
$([ "${LOG_DHCP}" = "1" ] && echo "log-facility=/var/log/dnsmasq.log")

EOF

# ---------------------------------------------------------------------------
# Static reservations — render `dhcp-host=` lines from the DHCP_HOSTS env
# var. Format is one entry per line, exactly what dnsmasq's dhcp-host
# directive expects (after the equals sign):
#
#   <MAC>,<NAME>,<IP>
#
# Example (set in topology.clab.yaml on the dhcp-pcn node):
#
#   env:
#     DHCP_HOSTS: |
#       2c:cf:67:4f:d3:09,l1-plc-01,10.20.30.47
#       b8:27:eb:78:85:77,l1-hp-01,10.20.30.48
#
# Why env-driven? Adding a new reservation shouldn't require rebuilding
# the image. The address plan in docs/naming-schema.md is the source of
# truth — this just gives the DHCP server enough state to enforce it.
# ---------------------------------------------------------------------------
if [ -n "${DHCP_HOSTS:-}" ]; then
    echo "# Static reservations from DHCP_HOSTS env" >>"$CFG"
    n=0
    echo "$DHCP_HOSTS" | while IFS= read -r line; do
        # Trim whitespace; skip blanks and comment lines
        line=$(echo "$line" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')
        case "$line" in
            ''|'#'*) continue ;;
        esac
        echo "dhcp-host=$line" >>"$CFG"
    done
    # Echo the count to startup log for visibility (the loop above runs
    # in a subshell so we re-count rather than using $n).
    echo "    reservations: $(grep -c '^dhcp-host=' "$CFG")"
else
    echo "    reservations: 0 (DHCP_HOSTS env unset)"
fi

# Wait for the listen interface to actually exist. Containerlab attaches
# the bridge-side veth (eth1) AFTER the container's entrypoint starts,
# so on cold start dnsmasq sees "unknown interface eth1" and crashes.
# Loop until the kernel reports the interface is present.
echo "==> waiting for ${LISTEN_IF} to be attached..."
for _ in $(seq 1 60); do
    if ip link show "${LISTEN_IF}" >/dev/null 2>&1; then
        break
    fi
    sleep 0.5
done
if ! ip link show "${LISTEN_IF}" >/dev/null 2>&1; then
    echo "FATAL: ${LISTEN_IF} never appeared after 30s — clab link missing?" >&2
    exit 1
fi

# Configure our own IP on the listen interface (containerlab's exec hooks
# may also do this — but on the first run we may beat them to it; on
# subsequent runs they've already done it. `ip addr replace` is a safe
# upsert either way).
ip addr replace "${SELF_IP}/${PREFIX}" dev "${LISTEN_IF}" 2>/dev/null || true
ip link set "${LISTEN_IF}" up 2>/dev/null || true

echo "==> OTLab DHCP starting"
echo "    interface : ${LISTEN_IF}"
echo "    network   : ${NETWORK}/${PREFIX}"
echo "    self      : ${SELF_IP}"
echo "    gateway   : ${GATEWAY}"
echo "    DNS       : ${DNS_SERVER}"
echo "    scope     : ${RANGE_START} -- ${RANGE_END}"
echo "    lease     : ${LEASE_TIME}"

exec dnsmasq --keep-in-foreground --conf-file="$CFG" --no-resolv --no-hosts
